# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9d8a91a81092c78f547dfdfe668aa13c0559c378b247d55c7f06eea008c6a2e6c7a0138b6dbe6b3ece5aefcc28eec4663806a0fcf338109b64c3252a51ad90

test:
  secret_key_base: d399c21572a1a307eb7e1d03f7264fce5b7937a97d0c5b56a19f5ebf1eabc9f192f5f7c8e92a9b86d4e7323181eeb53555147cf123da04b60668db4812d2feb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
